name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache-dependency-path: 'android/*.gradle*'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stankap-release-apk
          path: build/app/outputs/flutter-apk/*.apk
        if: success()
